global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
- job_name: 'rails'
  scheme: http
  metrics_path: '/metrics'
  static_configs:
    - targets:
      - 'rails:5000'
- job_name: 'sidekiq'
  scheme: http
  metrics_path: '/metrics'
  static_configs:
    - targets:
      - 'sidekiq:5100'
